// Sample data with image links
const listingsData = [
  {
    title: 'Cozy Cottage',
    description: 'A lovely cottage in the woods.',
    image: 'https://plus.unsplash.com/premium_photo-1661957883806-4f6d9ffff913?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 800,
    location: 'Lake Tahoe',
    country: 'USA',
    reviews: [],
  },
  {
    title: 'Beachfront Villa',
    description: 'A stunning villa with ocean views.',
    image: 'https://plus.unsplash.com/premium_photo-1661957883806-4f6d9ffff913?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 900,
    location: 'Malibu',
    country: 'USA',
    reviews: [],
  },
  {
    title: 'Rustic Farmhouse',
    description: 'A charming farmhouse surrounded by fields.',
    image: 'https://media.istockphoto.com/id/1197978080/photo/ban-rak-thai-the-most-beautiful-village-in-thailand.jpg?s=612x612&w=is&k=20&c=qKZ7rUBFQbmO2qVSYbkq8V6MyBlPuPakR_2hRzTvMLc=',
    price: 750,
    location: 'Napa Valley',
    country: 'USA',
    reviews: [],
  },
  {
    title: 'Luxury Penthouse',
    description: 'An elegant penthouse with a rooftop terrace.',
    image: 'https://media.istockphoto.com/id/1197978080/photo/ban-rak-thai-the-most-beautiful-village-in-thailand.jpg?s=612x612&w=is&k=20&c=qKZ7rUBFQbmO2qVSYbkq8V6MyBlPuPakR_2hRzTvMLc=',
    price: 1200,
    location: 'Miami',
    country: 'USA',
    reviews: [],
  },
  {
    title: 'Countryside Retreat',
    description: 'A peaceful retreat in the countryside.',
    image: 'https://images.unsplash.com/photo-1714240230527-a5d048cfc3f6?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 700,
    location: 'Hampshire',
    country: 'UK',
    reviews: [],
  },
  {
    title: 'Ski Resort Lodge',
    description: 'A cozy lodge perfect for ski enthusiasts.',
    image: 'https://images.unsplash.com/photo-1714240230274-94d05d790f97?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 850,
    location: 'Aspen',
    country: 'USA',
    reviews: [],
  },
  {
    title: 'Historic Castle',
    description: 'Experience living in a historic castle.',
    image: 'https://plus.unsplash.com/premium_photo-1667516467375-2c5c5c55f8fd?q=80&w=869&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 2000,
    location: 'Scotland',
    country: 'UK',
    reviews: [],
  },
  {
    title: 'Tropical Bungalow',
    description: 'A charming bungalow near the beach.',
    image: 'https://plus.unsplash.com/premium_photo-1664908253723-c16876ab1ad1?q=80&w=869&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 950,
    location: 'Hawaii',
    country: 'USA',
    reviews: [],
  },
  {
    title: 'Modern Chalet',
    description: 'A chic chalet with stunning mountain views.',
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?q=80&w=874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 780,
    location: 'Whistler',
    country: 'Canada',
    reviews: [],
  },
  {
    title: 'Riverside Cabin',
    description: 'A quaint cabin by the river.',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 720,
    location: 'Banff',
    country: 'Canada',
    reviews: [],
  },
  {
    title: 'Artistic Studio',
    description: 'A unique studio space for artists.',
    image: 'https://media.istockphoto.com/id/1197978080/photo/ban-rak-thai-the-most-beautiful-village-in-thailand.jpg?s=612x612&w=is&k=20&c=qKZ7rUBFQbmO2qVSYbkq8V6MyBlPuPakR_2hRzTvMLc=',
    price: 830,
    location: 'Paris',
    country: 'France',
    reviews: [],
  },
  {
    title: 'Secluded Retreat',
    description: 'A hidden gem perfect for relaxation.',
    image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 750,
    location: 'Tuscany',
    country: 'Italy',
    reviews: [],
  },
  {
    title: 'Lakeside Lodge',
    description: 'A serene lodge with beautiful lake views.',
    image: 'https://media.istockphoto.com/id/1424907972/photo/tropical-resort-at-sanya-china.jpg?s=612x612&w=is&k=20&c=5zck935Ukd_M2rEnNspu_8ypMq953CWGDafOIwUFZZk=',
    price: 900,
    location: 'Finger Lakes',
    country: 'USA',
    reviews: [],
  },
];

module.exports = { data: listingsData };
